before:
  hooks:
    - go mod tidy

builds:
  - 
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
    
    goarch:
      - amd64

archives:
  -
    id: binary
    format: binary
    
  - 
    id: tar.gz

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
