before:
  hooks:
    - go mod tidy

builds:
  - 
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
    
    goarch:
      - amd64

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
