---
sagify:

  train:
    input_s3_dir: s3://sagify-0.13.1/iris.csv
    output_s3_dir: s3://kenza-training-models
    ec2_type: ml.m5.large
    hyperparameters_file: hyperparams.json
    volume_size: 50
    timeout: 86400
      
    schedule:
      train_regularly:
        branch: test
        when: rate(1 hour)
        description: Train on test branch regularly
    
#     deploy:
#       instances_count: 1
#       ec2_type: ml.t2.medium

#   hyperparameter_optimization:
#     input_s3_dir: s3://sagify-0.13.1/iris.csv
#     output_s3_dir: s3://kenza-training-models
#     ec2_type: ml.m5.large
#     hyperparameter_ranges_file: tuning_hyperparameters.json
#     volume_size: 60
#     timeout: 86400
#     max_jobs: 2
#     max_parallel_jobs: 2
#     deploy:
#       instances_count: 1
#       ec2_type: ml.t2.medium
    
#     schedule:
#       tune_regularly:
#         branch: test
#         when: rate(1 hour)
#         description: Tune on test branch every hour

#   batch_transform:
  
#     instances_count: 1
#     ec2_type: ml.m5.large
#     features_s3_location: s3://test-sagify/test1/batch_input
#     predictions_s3_location: s3://test-sagify/features-output
#     model_s3_location: s3://kenza-training-models/kenza-45-240/output/model.tar.gz
    
#     schedule:
#       train_regularly:
#         branch: test
#         when: rate(1 hour)
#         description: Train on test branch regularly
#       weekday_evenings:
#         branch: test
#         when: cron(0 18 ? * MON-FRI *)
#         description: Weekday evenings
